name: yummy
description: "Yummy is a food platform for customers to order food from a wide variety of restaurants."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.3.3
  intl: ^0.19.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/categories/
    - assets/restaurants/
    - assets/profile_pics/
    - assets/food/